### ISSUE TITLE
Use `daq-cmake` or use similar installation paths as if using `daq_install()` 

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/triggeralgs#1]
If we want to have this package installed as a DAQ package, it would be best to modify its `CMakeLists.txt` to either use `daq-cmake` or use similar installation paths for `lib64, include`, as if using `daq_install()`.

Alternatively, we can use this package as an external UPS package. Then `CMakeLists.txt` will not be an issue here.

**Comment by philiprodrigues** [comment]
This is definitely a sensible suggestion. At the moment I'm a bit unsure of the long-term plan for `triggeralgs`. The initial idea was to have it not depend on the dunedaq framework so we could also use it in conjunction with the offline framework for, eg, trigger efficiency studies. I'm not sure whether this will actually turn out to be possible in the end, but it would be nice to have. I have discussions ongoing with a few people about this.

In the meantime, making the installation paths match the `daq_install()` ones is a good idea - I'll do that.

**Comment by philiprodrigues** [comment]
PR #2 implements the approach of making triggeralgs look like a daq-cmake package without actually depending on `daq-cmake`. @dingp could you take a look and see if it looks sensible to you?

**Comment by dingp** [comment]
I posted my comments on PR #2. I think it's ready to be merged, as long as corresponding changes in a PR is ready in the `trigger` repo.

Also, this repo does not have a `develop` branch. I've created one from master, but not yet set it to be the default branch yet, just in case I broke any of your workflow. 

Could you please change the default branch to `develop` (or let me know you are ready for the change)?
