### ISSUE TITLE
Atypical TXMaker Naming

### ISSUE THREAD

**Issue by aeoranday** [DUNE-DAQ/triggeralgs#83]
https://github.com/DUNE-DAQ/triggeralgs/blob/b146de11c70917dad70666fe40bbe5b8346e8c86/src/TAMakerADCSimpleWindowAlgorithm.cpp#L12

All other algorithms follow the naming scheme `TXMaker<Brief Name>Algorithm`, but this one appends `Plugin` to the end and should be removed.

**Comment by MRiganSUSX** [comment]
Fixed with https://github.com/DUNE-DAQ/triggeralgs/pull/85/files.
